### ISSUE TITLE
remove option for cg_depthSortParticles in UI

### ISSUE THREAD

**Issue by illwieckz** [UnvanquishedAssets/unvanquished_src.dpkdir#20]
Enabling `cg_bounceParticles` while disabling `cg_depthSortParticles` is wrong and produce issue users will report as bugs (like missing snow in chasm, or buildable remains not laying on floor).

Either `cg_bounceParticles` is enabled and does depth sort, either it's disabled. We may even remove the `cg_bounceParticles` cvar, but at least, we must remove the “Ensure over-lapping particles are rendered correctly” option from the UI.

There is no reason on earth to use `cg_bounceParticles` whithout `cg_depthSortParticles`.

**Comment by bmorel** [comment]
The problem is, there is no way AFAIK to make a cvar's value dependent on another cvar's value.
The best which could be done there would be to either:

* emit a warning when the values conflict, and select a valid configuration
* or emit a warning when conflicting values are set, and set coherent ones instead

**Comment by slipher** [comment]
Let's delete this cvar in the cgame? Don't see the point of having a "render things incorrectly" option

**Comment by illwieckz** [comment]
> Let's delete this cvar (cg_depthSortParticles) in the cgame? Don't see the point of having a "render things incorrectly" option

I agree.

**Comment by bmorel** [comment]
I agree too.

**Comment by illwieckz** [comment]
We probably still have to remove the UI part.
